import React from 'react';

export default function Classes (props) {
    return (
        <div style={{
            width: '100%',
            height: '100%',
            overflow: 'auto',
        }}>
          <div>
            <pre style={{lineHeight: '14px'}}>{graph.join('\n')}</pre>
          </div>
        </div>
    );
}

const graph = [
    '              @yanqirenshi/assh0le                +---------------------------------------------+',
    '              +-------+                           | Stylist                                     |',
    '              | Colon |                           |=============================================|',
    '              |=======|                           |---------------------------------------------|',
    '              |-------|                           |- makePool             (list)                |',
    '              +-------+                           |- makeIndexWpKeyParent (pool)                |',
    '                  ^                               |- data2pools           (data)                |',
    '                  |                               |- stylingWorkpackages  (style, scale, data)  |',
    '     +-----------------------------+              |- stylingWBS           (style, data, index)  |',
    '     | Rectum                      |              |- stylingHead          (style, pools)        |',
    '     |=============================|              |- stylingBody          (style, pools)        |',
    '     |- stylist                    |<-------------|- stylingFoot          (style, pools)        |',
    '     |-----------------------------|              |- stylingStage         (pools)               |',
    '     |- constructor  (params)      |              |- getTerm              (pools)               |',
    '     |- drawStage    (place, data) |              |- makeScale            (stage, term)         |',
    '     |- drawHead     (place, data) |              |- makeStage            (data, term, style)   |',
    '     |- drawHeadGrit (place, data) |              |- makeHeaderCells      (style, pools)        |',
    '     |- drawCell     (place, data) |              |- makeGrid             (cycle, style, pools) |',
    '     |- drawBody     (place, data) |              |- makeNow              (style, pools)        |',
    '     |- drawBodyGrid (place, data) |              |+ styling              (data, children)      |',
    '     |- drawFoot     (place, data) |              +---------------------------------------------+',
    '     |- drawRows     (place, data) |              ',
    '     |- drawNow      (place, data) |              +------------------------------------+',
    '     |+ draw         ()            |<-------------| Charts                             |',
    '     |+ drawBodyGrid (place, data) |              |====================================|',
    '     +-----------------------------+              |------------------------------------|',
    '                                                  |- drawTextsWithLink (mode, anchers) |',
    '                                                  |- drawTexts         (texts)         |',
    '                                                  |- drawResult        (rects)         |',
    '                                                  |- drawPlan          (rects)         |',
    '                                                  |- drawProgress      (rects)         |',
    '                                                  +------------------------------------+',
    '',
    '                     +----------------------------+',
    '                     | Element                    |',
    '                     |============================|',
    '                     |+ id                        |',
    '                     |- _size                     |',
    '                     |- _location                 |',
    '                     |- _children                 |',
    '                     |- core                      |',
    '                     |- style                     |',
    '                     |----------------------------|',
    '                     |+ constructor (data, style) |',
    '                     |+ size        (v)           |',
    '                     |+ location    (v)           |',
    '                     |+ children    (v)           |',
    '                     +----------------------------+',
    '                                 ^                 ',
    '                                 |                 ',
    '                +----------------+-------------------------------+-----------------------------------+----------------+-----------+-----------+-----------+   ',
    '                |                                                |                                   |                |           |           |           |   ',
    ' +-----------------------------------+    +---------------------------------------------+    +---------------+    +------+    +------+    +------+    +------+',
    ' | Wbs                               |    | Workpackage                                 |    | Stage         |    | Body |    | Cell |    | Foot |    | Head |',
    ' |===================================|    |=============================================|    |===============|    |======|    |======|    |======|    |======|',
    ' |-----------------------------------|    |- _label                                     |    |---------------|    |------|    |------|    |------|    |------|',
    ' |+ padding               ()         |    |- _plan                                      |    |+ padding   () |    +------+    +------+    +------+    +------+',
    ' |- layoutChildrenAddTemp (wp, tmp)  |    |- _result                                    |    |+ w         () |                                                ',
    ' |- layoutChildrenMakeTmp (children) |    |- _progress                                  |    |+ contentsW () |                                                ',
    ' |- layoutChildren        (children) |    |---------------------------------------------|    +---------------+                                                ',
    ' |- childrenH             (children) |    |+ constructor     (data, style)              |',
    ' |+ styling               (children) |    |- location        (v)                        |',
    ' +-----------------------------------+    |- parentId        ()                         |',
    '                                          |- url             ()                         |',
    '                                          |- stylingLabel    ()                         |',
    '                                          |- stylingPlan     (plan_w)                   |',
    '                                          |- stylingResult   (result_x, result_w)       |',
    '                                          |- stylingProgress (core, plan_w)             |',
    '                                          |- calRect         (type, core, scale, style) |',
    '                                          |+ styling         (scale)                    |',
    '                                          +---------------------------------------------+',
];
